[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build --workspace=api"

[deploy]
startCommand = "npm run start:prod --workspace=api"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10